### ISSUE TITLE
How to add it

### ISSUE THREAD

**Issue by wael1222** [ashish-y/item_availability_check#1]
hi could u explain me how to add it in my script or in the inspect page I came from the tutorial in youtube for stock checker

**Comment by ashish-y** [comment]
@wael1222 You can update the item list in the checkAvailabilty.py file. 
and run 
`python3 checkAvailability.py > result.log &`

It worked for me, but I'm not sure if BestBuy changed anything on their website. So you might have to inspect the HTML on the website.
